### ISSUE TITLE
Looking for your scripts to go with eww?

### ISSUE THREAD

**Issue by Dobbie03** [Animeshz/linux-desktop#1]
Hi there, I love your implementation of eww as a bar.  Can you please share the accompanying scripts to go with it?

Thanks

**Comment by Animeshz** [comment]
Hey! They're under `.config/eww/scripts`

A few scripts update eww var passed as first argument by eww cli (so need to be in path) like volume script which changes the speaker-headphone icon on acpi-events, but I'll have to make them portable so can be used anywhere even in shell 👀. Scripts are implemented as listenvar (eww) which is same as tail in polybar, they push newline (react to events) and bar updates it.

(Note: wifi ssid (oh hover sliding) and temp/weather info is not implemented)

**Comment by Dobbie03** [comment]
Thanks for the reply.  That makes sense.  Thank you, cool setup by the way.

**Comment by Animeshz** [comment]
@Dobbie03 Oh hey, if you're wondering why the css isn't  applied to the workspace section, its due to elkowar/eww#267 (dynamic/literal objects do not have access to the styling context) a temp fix is [here](https://github.com/Animeshz/eww/tree/literal-variable-fix) which cause a bit of mem leak if you add/remove the workspaces though (580KiB / 5k addition and 5k workspace merge).

```
  ~ >>> free | awk '/Mem/ {print $3}'; for i in 1..5000; do herbstclient add 6; herbstclient merge_tag 6 5; done; free | awk '/Mem/ {print $3}'
1733852
1734432
```

I often don't add workspaces more than 20 times so I'm just living with this temporary fix :P (merge it with upstream:master on a local fork)

https://github.com/Animeshz/linux-desktop/blob/0ea9c0c129bdd17690d1746468f1a01fefd22b04/.config/eww/scripts/xworkspaces#L16 And styler pipe program is [here](https://github.com/Animeshz/scripts) for making the workspace name as superscript names as in image.

**Comment by Dobbie03** [comment]
Brilliant, thanks for letting me know.
Cheers
